# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/morsss/Documents/Code/summer-practice-2026

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/morsss/Documents/Code/summer-practice-2026

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/morsss/Documents/Code/summer-practice-2026/CMakeFiles /Users/morsss/Documents/Code/summer-practice-2026//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/morsss/Documents/Code/summer-practice-2026/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Platformer

# Build rule for target.
Platformer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Platformer
.PHONY : Platformer

# fast build rule for target.
Platformer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/build
.PHONY : Platformer/fast

src/core/input.o: src/core/input.cpp.o
.PHONY : src/core/input.o

# target to build an object file
src/core/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/core/input.cpp.o
.PHONY : src/core/input.cpp.o

src/core/input.i: src/core/input.cpp.i
.PHONY : src/core/input.i

# target to preprocess a source file
src/core/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/core/input.cpp.i
.PHONY : src/core/input.cpp.i

src/core/input.s: src/core/input.cpp.s
.PHONY : src/core/input.s

# target to generate assembly for a file
src/core/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/core/input.cpp.s
.PHONY : src/core/input.cpp.s

src/game/grass.o: src/game/grass.cpp.o
.PHONY : src/game/grass.o

# target to build an object file
src/game/grass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/grass.cpp.o
.PHONY : src/game/grass.cpp.o

src/game/grass.i: src/game/grass.cpp.i
.PHONY : src/game/grass.i

# target to preprocess a source file
src/game/grass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/grass.cpp.i
.PHONY : src/game/grass.cpp.i

src/game/grass.s: src/game/grass.cpp.s
.PHONY : src/game/grass.s

# target to generate assembly for a file
src/game/grass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/grass.cpp.s
.PHONY : src/game/grass.cpp.s

src/game/lighting.o: src/game/lighting.cpp.o
.PHONY : src/game/lighting.o

# target to build an object file
src/game/lighting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/lighting.cpp.o
.PHONY : src/game/lighting.cpp.o

src/game/lighting.i: src/game/lighting.cpp.i
.PHONY : src/game/lighting.i

# target to preprocess a source file
src/game/lighting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/lighting.cpp.i
.PHONY : src/game/lighting.cpp.i

src/game/lighting.s: src/game/lighting.cpp.s
.PHONY : src/game/lighting.s

# target to generate assembly for a file
src/game/lighting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/lighting.cpp.s
.PHONY : src/game/lighting.cpp.s

src/game/player.o: src/game/player.cpp.o
.PHONY : src/game/player.o

# target to build an object file
src/game/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/player.cpp.o
.PHONY : src/game/player.cpp.o

src/game/player.i: src/game/player.cpp.i
.PHONY : src/game/player.i

# target to preprocess a source file
src/game/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/player.cpp.i
.PHONY : src/game/player.cpp.i

src/game/player.s: src/game/player.cpp.s
.PHONY : src/game/player.s

# target to generate assembly for a file
src/game/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/player.cpp.s
.PHONY : src/game/player.cpp.s

src/game/tilemap.o: src/game/tilemap.cpp.o
.PHONY : src/game/tilemap.o

# target to build an object file
src/game/tilemap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/tilemap.cpp.o
.PHONY : src/game/tilemap.cpp.o

src/game/tilemap.i: src/game/tilemap.cpp.i
.PHONY : src/game/tilemap.i

# target to preprocess a source file
src/game/tilemap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/tilemap.cpp.i
.PHONY : src/game/tilemap.cpp.i

src/game/tilemap.s: src/game/tilemap.cpp.s
.PHONY : src/game/tilemap.s

# target to generate assembly for a file
src/game/tilemap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/game/tilemap.cpp.s
.PHONY : src/game/tilemap.cpp.s

src/levels/screen_01.o: src/levels/screen_01.cpp.o
.PHONY : src/levels/screen_01.o

# target to build an object file
src/levels/screen_01.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/levels/screen_01.cpp.o
.PHONY : src/levels/screen_01.cpp.o

src/levels/screen_01.i: src/levels/screen_01.cpp.i
.PHONY : src/levels/screen_01.i

# target to preprocess a source file
src/levels/screen_01.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/levels/screen_01.cpp.i
.PHONY : src/levels/screen_01.cpp.i

src/levels/screen_01.s: src/levels/screen_01.cpp.s
.PHONY : src/levels/screen_01.s

# target to generate assembly for a file
src/levels/screen_01.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/levels/screen_01.cpp.s
.PHONY : src/levels/screen_01.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/render/lighting_draw.o: src/render/lighting_draw.cpp.o
.PHONY : src/render/lighting_draw.o

# target to build an object file
src/render/lighting_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/render/lighting_draw.cpp.o
.PHONY : src/render/lighting_draw.cpp.o

src/render/lighting_draw.i: src/render/lighting_draw.cpp.i
.PHONY : src/render/lighting_draw.i

# target to preprocess a source file
src/render/lighting_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/render/lighting_draw.cpp.i
.PHONY : src/render/lighting_draw.cpp.i

src/render/lighting_draw.s: src/render/lighting_draw.cpp.s
.PHONY : src/render/lighting_draw.s

# target to generate assembly for a file
src/render/lighting_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/render/lighting_draw.cpp.s
.PHONY : src/render/lighting_draw.cpp.s

src/render/renderer.o: src/render/renderer.cpp.o
.PHONY : src/render/renderer.o

# target to build an object file
src/render/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/render/renderer.cpp.o
.PHONY : src/render/renderer.cpp.o

src/render/renderer.i: src/render/renderer.cpp.i
.PHONY : src/render/renderer.i

# target to preprocess a source file
src/render/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/render/renderer.cpp.i
.PHONY : src/render/renderer.cpp.i

src/render/renderer.s: src/render/renderer.cpp.s
.PHONY : src/render/renderer.s

# target to generate assembly for a file
src/render/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/render/renderer.cpp.s
.PHONY : src/render/renderer.cpp.s

src/render/tilemap_draw.o: src/render/tilemap_draw.cpp.o
.PHONY : src/render/tilemap_draw.o

# target to build an object file
src/render/tilemap_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/render/tilemap_draw.cpp.o
.PHONY : src/render/tilemap_draw.cpp.o

src/render/tilemap_draw.i: src/render/tilemap_draw.cpp.i
.PHONY : src/render/tilemap_draw.i

# target to preprocess a source file
src/render/tilemap_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/render/tilemap_draw.cpp.i
.PHONY : src/render/tilemap_draw.cpp.i

src/render/tilemap_draw.s: src/render/tilemap_draw.cpp.s
.PHONY : src/render/tilemap_draw.s

# target to generate assembly for a file
src/render/tilemap_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/render/tilemap_draw.cpp.s
.PHONY : src/render/tilemap_draw.cpp.s

src/screens/game_screen.o: src/screens/game_screen.cpp.o
.PHONY : src/screens/game_screen.o

# target to build an object file
src/screens/game_screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/game_screen.cpp.o
.PHONY : src/screens/game_screen.cpp.o

src/screens/game_screen.i: src/screens/game_screen.cpp.i
.PHONY : src/screens/game_screen.i

# target to preprocess a source file
src/screens/game_screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/game_screen.cpp.i
.PHONY : src/screens/game_screen.cpp.i

src/screens/game_screen.s: src/screens/game_screen.cpp.s
.PHONY : src/screens/game_screen.s

# target to generate assembly for a file
src/screens/game_screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/game_screen.cpp.s
.PHONY : src/screens/game_screen.cpp.s

src/screens/loading_screen.o: src/screens/loading_screen.cpp.o
.PHONY : src/screens/loading_screen.o

# target to build an object file
src/screens/loading_screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/loading_screen.cpp.o
.PHONY : src/screens/loading_screen.cpp.o

src/screens/loading_screen.i: src/screens/loading_screen.cpp.i
.PHONY : src/screens/loading_screen.i

# target to preprocess a source file
src/screens/loading_screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/loading_screen.cpp.i
.PHONY : src/screens/loading_screen.cpp.i

src/screens/loading_screen.s: src/screens/loading_screen.cpp.s
.PHONY : src/screens/loading_screen.s

# target to generate assembly for a file
src/screens/loading_screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/loading_screen.cpp.s
.PHONY : src/screens/loading_screen.cpp.s

src/screens/menu_screen.o: src/screens/menu_screen.cpp.o
.PHONY : src/screens/menu_screen.o

# target to build an object file
src/screens/menu_screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/menu_screen.cpp.o
.PHONY : src/screens/menu_screen.cpp.o

src/screens/menu_screen.i: src/screens/menu_screen.cpp.i
.PHONY : src/screens/menu_screen.i

# target to preprocess a source file
src/screens/menu_screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/menu_screen.cpp.i
.PHONY : src/screens/menu_screen.cpp.i

src/screens/menu_screen.s: src/screens/menu_screen.cpp.s
.PHONY : src/screens/menu_screen.s

# target to generate assembly for a file
src/screens/menu_screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/menu_screen.cpp.s
.PHONY : src/screens/menu_screen.cpp.s

src/screens/pause_screen.o: src/screens/pause_screen.cpp.o
.PHONY : src/screens/pause_screen.o

# target to build an object file
src/screens/pause_screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/pause_screen.cpp.o
.PHONY : src/screens/pause_screen.cpp.o

src/screens/pause_screen.i: src/screens/pause_screen.cpp.i
.PHONY : src/screens/pause_screen.i

# target to preprocess a source file
src/screens/pause_screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/pause_screen.cpp.i
.PHONY : src/screens/pause_screen.cpp.i

src/screens/pause_screen.s: src/screens/pause_screen.cpp.s
.PHONY : src/screens/pause_screen.s

# target to generate assembly for a file
src/screens/pause_screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/pause_screen.cpp.s
.PHONY : src/screens/pause_screen.cpp.s

src/screens/settings_screen.o: src/screens/settings_screen.cpp.o
.PHONY : src/screens/settings_screen.o

# target to build an object file
src/screens/settings_screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/settings_screen.cpp.o
.PHONY : src/screens/settings_screen.cpp.o

src/screens/settings_screen.i: src/screens/settings_screen.cpp.i
.PHONY : src/screens/settings_screen.i

# target to preprocess a source file
src/screens/settings_screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/settings_screen.cpp.i
.PHONY : src/screens/settings_screen.cpp.i

src/screens/settings_screen.s: src/screens/settings_screen.cpp.s
.PHONY : src/screens/settings_screen.s

# target to generate assembly for a file
src/screens/settings_screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/settings_screen.cpp.s
.PHONY : src/screens/settings_screen.cpp.s

src/screens/transition.o: src/screens/transition.cpp.o
.PHONY : src/screens/transition.o

# target to build an object file
src/screens/transition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/transition.cpp.o
.PHONY : src/screens/transition.cpp.o

src/screens/transition.i: src/screens/transition.cpp.i
.PHONY : src/screens/transition.i

# target to preprocess a source file
src/screens/transition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/transition.cpp.i
.PHONY : src/screens/transition.cpp.i

src/screens/transition.s: src/screens/transition.cpp.s
.PHONY : src/screens/transition.s

# target to generate assembly for a file
src/screens/transition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Platformer.dir/build.make CMakeFiles/Platformer.dir/src/screens/transition.cpp.s
.PHONY : src/screens/transition.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Platformer"
	@echo "... src/core/input.o"
	@echo "... src/core/input.i"
	@echo "... src/core/input.s"
	@echo "... src/game/grass.o"
	@echo "... src/game/grass.i"
	@echo "... src/game/grass.s"
	@echo "... src/game/lighting.o"
	@echo "... src/game/lighting.i"
	@echo "... src/game/lighting.s"
	@echo "... src/game/player.o"
	@echo "... src/game/player.i"
	@echo "... src/game/player.s"
	@echo "... src/game/tilemap.o"
	@echo "... src/game/tilemap.i"
	@echo "... src/game/tilemap.s"
	@echo "... src/levels/screen_01.o"
	@echo "... src/levels/screen_01.i"
	@echo "... src/levels/screen_01.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render/lighting_draw.o"
	@echo "... src/render/lighting_draw.i"
	@echo "... src/render/lighting_draw.s"
	@echo "... src/render/renderer.o"
	@echo "... src/render/renderer.i"
	@echo "... src/render/renderer.s"
	@echo "... src/render/tilemap_draw.o"
	@echo "... src/render/tilemap_draw.i"
	@echo "... src/render/tilemap_draw.s"
	@echo "... src/screens/game_screen.o"
	@echo "... src/screens/game_screen.i"
	@echo "... src/screens/game_screen.s"
	@echo "... src/screens/loading_screen.o"
	@echo "... src/screens/loading_screen.i"
	@echo "... src/screens/loading_screen.s"
	@echo "... src/screens/menu_screen.o"
	@echo "... src/screens/menu_screen.i"
	@echo "... src/screens/menu_screen.s"
	@echo "... src/screens/pause_screen.o"
	@echo "... src/screens/pause_screen.i"
	@echo "... src/screens/pause_screen.s"
	@echo "... src/screens/settings_screen.o"
	@echo "... src/screens/settings_screen.i"
	@echo "... src/screens/settings_screen.s"
	@echo "... src/screens/transition.o"
	@echo "... src/screens/transition.i"
	@echo "... src/screens/transition.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

